apiVersion: v1
entries:
  casdoor-helm-charts:
  - apiVersion: v2
    appVersion: v1.527.0
    created: "2024-02-06T12:33:33.209886166Z"
    description: A Helm chart for Kubernetes
    digest: 06f5ec82ecd225ad1c3fc4813623beec299c8fcf833e26871e0adcdd04ef2175
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.527.0.tgz
    version: v1.527.0
  - apiVersion: v2
    appVersion: v1.526.0
    created: "2024-02-06T08:58:23.321776076Z"
    description: A Helm chart for Kubernetes
    digest: a9cde1013c1b050e5e89ab23c1841c886f782cce21e6a41d03aaeffa87f9b990
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.526.0.tgz
    version: v1.526.0
  - apiVersion: v2
    appVersion: v1.524.0
    created: "2024-02-03T02:16:36.560146021Z"
    description: A Helm chart for Kubernetes
    digest: 8959a2062e00b02ebb35a33f5be7fd2f267fdda85a23a1a12c213d83346099e0
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.524.0.tgz
    version: v1.524.0
  - apiVersion: v2
    appVersion: v1.523.0
    created: "2024-02-02T13:28:30.990370334Z"
    description: A Helm chart for Kubernetes
    digest: a85406083ea4cc479b4590f02383122b819aa7421a586591528964f9247629b1
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.523.0.tgz
    version: v1.523.0
  - apiVersion: v2
    appVersion: v1.522.0
    created: "2024-02-02T02:38:42.457741791Z"
    description: A Helm chart for Kubernetes
    digest: 0fdf4a681705937e1679690ae1da10b87c7652eb3c64b799f89c65a16799c787
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.522.0.tgz
    version: v1.522.0
  - apiVersion: v2
    appVersion: v1.521.0
    created: "2024-02-01T10:05:48.821728673Z"
    description: A Helm chart for Kubernetes
    digest: 75e610c4fecddf1c8f333e532648deb07f6d1d3c2be4078d757a74978a50db13
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.521.0.tgz
    version: v1.521.0
  - apiVersion: v2
    appVersion: v1.520.0
    created: "2024-02-01T09:44:17.917942046Z"
    description: A Helm chart for Kubernetes
    digest: e598623d15df84a952d9433bcf692b07833d02a7c9918f8216ffbf6f87750e67
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.520.0.tgz
    version: v1.520.0
  - apiVersion: v2
    appVersion: v1.519.0
    created: "2024-01-31T15:30:17.35579161Z"
    description: A Helm chart for Kubernetes
    digest: 2766d2e81be7eba4eeeff876373ab5065c4e90e1fec86202b707afe8d56020f5
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.519.0.tgz
    version: v1.519.0
  - apiVersion: v2
    appVersion: v1.518.0
    created: "2024-01-30T16:21:10.54974967Z"
    description: A Helm chart for Kubernetes
    digest: 341a39c2541dad05d3704e6da28d4d1e9cd1e69a80be9f6562be200ed1511f6b
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.518.0.tgz
    version: v1.518.0
  - apiVersion: v2
    appVersion: v1.517.0
    created: "2024-01-30T15:34:07.93456698Z"
    description: A Helm chart for Kubernetes
    digest: 895147ab81c9e6b15c0c1eeb734d4ab2543de057a30f81731f2eb39e7171a1a8
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.517.0.tgz
    version: v1.517.0
  - apiVersion: v2
    appVersion: v1.516.0
    created: "2024-01-30T11:22:59.783826246Z"
    description: A Helm chart for Kubernetes
    digest: 87f3be017390dad8ec3e5be823e61c30a4afee1479e450fe196f21657f376483
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.516.0.tgz
    version: v1.516.0
  - apiVersion: v2
    appVersion: v1.515.0
    created: "2024-01-29T02:19:08.37920762Z"
    description: A Helm chart for Kubernetes
    digest: c143bc0380e0f12faddc7e9647e447a2422ec806d93327a97e33b3833453d7bd
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.515.0.tgz
    version: v1.515.0
  - apiVersion: v2
    appVersion: v1.514.0
    created: "2024-01-28T09:01:37.752118976Z"
    description: A Helm chart for Kubernetes
    digest: 1f69b376cc43c1e195beaff925d4416cd0dbb8531cd88f722b63ce00ca07b7af
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.514.0.tgz
    version: v1.514.0
  - apiVersion: v2
    appVersion: v1.513.0
    created: "2024-01-27T17:22:59.703497624Z"
    description: A Helm chart for Kubernetes
    digest: c061b39b3c9a21289baf3a877970c3723f776c71bbb5b2aac0b7c45b20ba44c9
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.513.0.tgz
    version: v1.513.0
  - apiVersion: v2
    appVersion: v1.512.0
    created: "2024-01-26T00:41:29.444372297Z"
    description: A Helm chart for Kubernetes
    digest: 2ff693a37859d793b8d34a6df95e2144ea4bc6a5df2e1a6434b94e63261d1a6d
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.512.0.tgz
    version: v1.512.0
  - apiVersion: v2
    appVersion: v1.511.0
    created: "2024-01-23T12:07:22.049692317Z"
    description: A Helm chart for Kubernetes
    digest: e7057654c808827f62b1685885071efc565e568bc6fad28c484bbf8289085b12
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.511.0.tgz
    version: v1.511.0
  - apiVersion: v2
    appVersion: v1.510.0
    created: "2024-01-21T18:40:21.691631583Z"
    description: A Helm chart for Kubernetes
    digest: acd83f66228d3ba20cbb057e8bde13773c0ff238bc64833bb1b19c285eee8435
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.510.0.tgz
    version: v1.510.0
  - apiVersion: v2
    appVersion: v1.509.0
    created: "2024-01-20T14:03:57.497500104Z"
    description: A Helm chart for Kubernetes
    digest: cc3637c6ad03ae1df30bca9066dc9dbed06c646308ada9e0e2ce5b99940eeaa1
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.509.0.tgz
    version: v1.509.0
  - apiVersion: v2
    appVersion: v1.508.0
    created: "2024-01-20T08:15:03.555926244Z"
    description: A Helm chart for Kubernetes
    digest: 5854e0d5a1e0cea3066f4acdabf01f05f9b390b7d92f4a6fd55da5013a23b30a
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.508.0.tgz
    version: v1.508.0
  - apiVersion: v2
    appVersion: v1.507.0
    created: "2024-01-19T14:28:21.170527579Z"
    description: A Helm chart for Kubernetes
    digest: 0f834b909782a702c981c73e3a3cfcace4faba295429323da8c1a37718605f81
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.507.0.tgz
    version: v1.507.0
  - apiVersion: v2
    appVersion: v1.506.0
    created: "2024-01-19T08:47:38.574116102Z"
    description: A Helm chart for Kubernetes
    digest: af805c8ecd9ff30cf6e363437da53355c75e6f0955e480b9af584199575cdda4
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.506.0.tgz
    version: v1.506.0
  - apiVersion: v2
    appVersion: v1.505.0
    created: "2024-01-18T13:15:10.086236752Z"
    description: A Helm chart for Kubernetes
    digest: dd987741237cbf3ecdebe4ab3197f60551ff513d4dfcde514ba1ecbc9bc03468
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.505.0.tgz
    version: v1.505.0
  - apiVersion: v2
    appVersion: v1.504.0
    created: "2024-01-17T05:23:21.009165397Z"
    description: A Helm chart for Kubernetes
    digest: 791edb91b417cd89841605d034af4de62d9f6d5e1bf9293778c2f654130fd8a5
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.504.0.tgz
    version: v1.504.0
  - apiVersion: v2
    appVersion: v1.503.0
    created: "2024-01-15T10:28:22.168684063Z"
    description: A Helm chart for Kubernetes
    digest: 7bd9beece3eae33622273306f772758a6f827cb11ecf98f097e2ff56f3fc13f0
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.503.0.tgz
    version: v1.503.0
  - apiVersion: v2
    appVersion: v1.502.0
    created: "2024-01-15T06:13:59.012071746Z"
    description: A Helm chart for Kubernetes
    digest: b1f17211650a19c611c0df1999ce1a4f5952912623d5acd6f56bf0c0eca8ed3b
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.502.0.tgz
    version: v1.502.0
  - apiVersion: v2
    appVersion: v1.501.0
    created: "2024-01-15T02:30:49.912499904Z"
    description: A Helm chart for Kubernetes
    digest: e4002420c653e401e45b5945f806e735ae01043b673e3cd8c814bb3205f808f2
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-v1.501.0.tgz
    version: v1.501.0
  - apiVersion: v2
    appVersion: v1.499.0
    created: "2024-01-13T08:25:19.954715378Z"
    description: A Helm chart for Kubernetes
    digest: b3d72700e132c672cd7320b0d85ccbe02a13688f001581181e3b41a00feae0f8
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.5.tgz
    version: 0.4.5
  - apiVersion: v2
    appVersion: v1.498.0
    created: "2024-01-13T03:52:38.843292507Z"
    description: A Helm chart for Kubernetes
    digest: 9b136a3fbf283b45b9dead5ca189a6db48d9307378127861f527e40f51213961
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.4.tgz
    version: 0.4.4
  - apiVersion: v2
    appVersion: v1.497.0
    created: "2024-01-11T08:25:06.782374644Z"
    description: A Helm chart for Kubernetes
    digest: 847fa0aab2d7f98f9a1b5ab6442015c8e6338f026b03bb65b121b58b325f6d9c
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.3.tgz
    version: 0.4.3
generated: "2024-02-06T12:33:33.209281159Z"
