apiVersion: v1
entries:
  casdoor-helm-charts:
  - apiVersion: v2
    appVersion: v1.499.0
    created: "2024-01-13T08:25:19.954715378Z"
    description: A Helm chart for Kubernetes
    digest: b3d72700e132c672cd7320b0d85ccbe02a13688f001581181e3b41a00feae0f8
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.5.tgz
    version: 0.4.5
  - apiVersion: v2
    appVersion: v1.498.0
    created: "2024-01-13T03:52:38.843292507Z"
    description: A Helm chart for Kubernetes
    digest: 9b136a3fbf283b45b9dead5ca189a6db48d9307378127861f527e40f51213961
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.4.tgz
    version: 0.4.4
  - apiVersion: v2
    appVersion: v1.497.0
    created: "2024-01-11T08:25:06.782374644Z"
    description: A Helm chart for Kubernetes
    digest: 847fa0aab2d7f98f9a1b5ab6442015c8e6338f026b03bb65b121b58b325f6d9c
    name: casdoor-helm-charts
    type: application
    urls:
    - oci://registry-1.docker.io/casbin/casdoor-helm-charts-0.4.3.tgz
    version: 0.4.3
generated: "2024-01-13T08:25:19.954106374Z"
